### ISSUE TITLE
action mysql.insert has unicode issue

### ISSUE THREAD

**Issue by leoxhj** [StackStorm-Exchange/stackstorm-mysql#7]
action: mysql.insert has unicode issue.

update mysql/actions/lib/base.py and mysql/action/insert.py solve problem

for file base.py
added "chartset='utf8'" to method manual_conn

for file insert.py
two solutions:

- removed 'u' from query = u"INSERT INTO {} ({}) VALUES ({})".format(table.encode('utf-8'), columns, values)

- add one new line 
values = values.decode('utf-8')

test data: 

{"name": "test_020", "description": "test_001", "version": "0.1.0", "author": "hj_xu", "organization": "上海"}

**Comment by LindsayHill** [comment]
I have just done some tests with this, and the only changed needed was this one:

> removed 'u' from query = u"INSERT INTO {} ({}) VALUES ({})".format(table.encode('utf-8'), columns, values)

The charset default is utf-8,so that one was not needed. Adding `values = values.decode('utf-8')` caused other issues.

Resolved with #10
